<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LLamaSharp" Version="0.12.0" />
    <PackageReference Include="LLamaSharp.Backend.Cpu" Version="0.12.0" />
  </ItemGroup>
</Project>
