<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>DsiAgentic.Learning</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DsiAgentic.Core\DsiAgentic.Core.csproj" />
    <ProjectReference Include="..\DsiAgentic.Brains\DsiAgentic.Brains.csproj" />
  </ItemGroup>
</Project>
