<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\NexusBrain.Core\NexusBrain.Core.csproj" />
    <ProjectReference Include="..\NexusBrain.Indicators\NexusBrain.Indicators.csproj" />
    <ProjectReference Include="..\NexusBrain.Brain\NexusBrain.Brain.csproj" />
    <ProjectReference Include="..\NexusBrain.Divergence\NexusBrain.Divergence.csproj" />
    <ProjectReference Include="..\NexusBrain.Forex\NexusBrain.Forex.csproj" />
    <ProjectReference Include="..\NexusBrain.Memory\NexusBrain.Memory.csproj" />
    <ProjectReference Include="..\NexusBrain.Deriv\NexusBrain.Deriv.csproj" />
  </ItemGroup>
</Project>
